export const verificationLabels = [
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerFname', label: 'Name' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerDob', label: 'Date of Birth' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerGender', label: 'Gender' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtRace', label: 'Race' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtEdctn', label: 'Education' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerOccupation', label: 'Occupation' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerHomeUSAddr1Addr2', label: 'Home Address Lines 1 and 2' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerHomeUSCityStZip', label: 'Home Address City, State, and Zipcode' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerMailUSAddr1Addr2', label: 'Mailing Address Lines 1 and 2' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerMailUSCityStZip', label: 'Mailing Address City, State, and Zipcode' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerCitznFlg', label: 'U.S. Citizen' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerTel1', label: 'First 3 Digits of Phone Number' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerTel2', label: 'Fourth, fifth, and sixth digits of Phone Number' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerTel3', label: 'Last 4 digits of Phone Number' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerTelExt', label: 'Phone Number Extension' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerAltTel1', label: 'First 3 Digits of Alternate Phone Number' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerAltTel2', label: 'Fourth, fifth, and sixth digits of Alternate Phone Number' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerAltTel3', label: 'Last 4 digits of Alternate Phone Number' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerAltTelExt', label: 'Alternate Phone Number Extension' },
  { id: 'ContentPlaceHolder1_ClaimantProfileTab_tpnlVerification_txtVerEmail', label: 'Email' },
];
