import {
  globalTestsNew,
  globalTestsOld,
  EXAMPLE_REASON_FOR_LEAVE_DATA_INJURY_DETAILS
} from "../shared";
import { encodeDecode } from '../../../../src/claimApplication/utils';

const PAGE_ID = 'verification';
const URL = 'ClaimantDisabililty';
const FIXTURE = "./cypress/fixtures/claimApplication/leaveInformationVerification/leaveInformationVerification.html";
const FIXTURE_WITH_WORKERS_COMP_YES = "./cypress/fixtures/claimApplication/leaveInformationVerification/leaveInformationVerificationWithCompYes.html";
const FIXTURE_WITH_NOT_APPROVED_BUT_RECEIVED_WC = "./cypress/fixtures/claimApplication/leaveInformationVerification/leaveInformationVerificationDeterminationNo.html";
const FIXTURE_WITH_INTL_DOCTOR = "cypress/fixtures/claimApplication/leaveInformationVerification/leaveInformationVerificationWithIntlDoc.html";

describe("Disability Verification page", () => {
  function checkPostData(interception) {
    const formData = interception.request.body;
    cy.checkCommonPostData(formData);
    expect(formData).to.include('__EVENTTARGET=ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24btncontinueVer&__EVENTARGUMENT=&ContentPlaceHolder1_ClaimantDisabilityTab_ClientState=%7B%22ActiveTabIndex%22%3A5%2C%22TabState%22%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%5D%7D&');
    expect(formData).to.include('ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnPregFlg=N&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtLDW=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnRTWFlg=Y&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtRTW=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtExpRDTW=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnConflictType=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnTDIPayCode=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabDoctor%24hdnInjCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabWC%24hdnNoClaimCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tbpnlLatePayment%24hdnLPay=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDate=05%2F05%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVetDtLast=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerReturn=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerRetWork=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDesc=pregnancy&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocName=Test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocStreet=test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddr2=45+MAIN+STREET++45+MAIN+STREET&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocCity=TRENTON&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip1=07765&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocVerZip=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel=804&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel2=294&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel3=4544&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTelExt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtHospVer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24TxtVerInjWk=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpNm=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCity=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpState=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZipCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjDt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWcComp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWCExp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDeter=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTempWC=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenefits=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDPayingState=CA&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDStatusPending=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfStartDate=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfEndDate=06%2F11%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSBenf=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDAStatus=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDADate=05%2F01%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIbenfRecvd=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIBPayingState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUI_Pend=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenStDt=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenEndDt=05%2F05%2F2027&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24lblFIT=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtAmtWK=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtRsnLate=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24VerDisab=rbtnDisabsYes');
  }

  function checkDisabilityPostData(interception) {
    const formData = interception.request.body;
    cy.checkCommonPostData(formData);
    expect(formData).to.include('__EVENTTARGET=&__EVENTARGUMENT=&ContentPlaceHolder1_ClaimantDisabilityTab_ClientState=%7B%22ActiveTabIndex%22%3A5%2C%22TabState%22%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%5D%7D&');
    expect(formData).to.include('ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip1=07765&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocVerZip=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel=804&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel2=294&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel3=4544&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTelExt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtHospVer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24TxtVerInjWk=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpNm=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCity=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpState=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZipCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjDt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWcComp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWCExp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDeter=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTempWC=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenefits=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDPayingState=CA&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDStatusPending=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfStartDate=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfEndDate=06%2F11%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSBenf=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDAStatus=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDADate=05%2F01%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIbenfRecvd=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIBPayingState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUI_Pend=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenStDt=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenEndDt=05%2F05%2F2027&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24lblFIT=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtAmtWK=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtRsnLate=');
  }

  function checkMedicalPostData(interception) {
    const formData = interception.request.body;
    cy.checkCommonPostData(formData);
    expect(formData).to.include('__EVENTTARGET=&__EVENTARGUMENT=&ContentPlaceHolder1_ClaimantDisabilityTab_ClientState=%7B%22ActiveTabIndex%22%3A5%2C%22TabState%22%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%5D%7D&');
    expect(formData).to.include('ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnPregFlg=N&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtLDW=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnRTWFlg=Y&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtRTW=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtExpRDTW=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnConflictType=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnTDIPayCode=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabDoctor%24hdnInjCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabWC%24hdnNoClaimCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tbpnlLatePayment%24hdnLPay=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDate=05%2F05%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVetDtLast=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerReturn=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerRetWork=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24btnVerDisab=EDIT&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDesc=pregnancy&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocName=Test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocStreet=test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddr2=45+MAIN+STREET++45+MAIN+STREET&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocCity=TRENTON&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip1=07765&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocVerZip=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel=804&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel2=294&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel3=4544&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTelExt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtHospVer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24TxtVerInjWk=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpNm=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCity=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpState=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZipCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjDt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWcComp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWCExp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDeter=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTempWC=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenefits=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDPayingState=CA&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDStatusPending=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfStartDate=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfEndDate=06%2F11%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSBenf=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDAStatus=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDADate=05%2F01%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIbenfRecvd=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIBPayingState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUI_Pend=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenStDt=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenEndDt=05%2F05%2F2027&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24lblFIT=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtAmtWK=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtRsnLate=');
  }

  function checkWorkPostData(interception) {
    const formData = interception.request.body;
    cy.checkCommonPostData(formData);
    expect(formData).to.include('__EVENTTARGET=&__EVENTARGUMENT=&ContentPlaceHolder1_ClaimantDisabilityTab_ClientState=%7B%22ActiveTabIndex%22%3A5%2C%22TabState%22%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%5D%7D&');
    expect(formData).to.include('ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip1=07765&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocVerZip=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel=804&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel2=294&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel3=4544&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTelExt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtHospVer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24BtnWREdit=EDIT&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24TxtVerInjWk=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpNm=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCity=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpState=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZipCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjDt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWcComp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWCExp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDeter=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTempWC=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenefits=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDPayingState=CA&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDStatusPending=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfStartDate=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfEndDate=06%2F11%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSBenf=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDAStatus=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDADate=05%2F01%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIbenfRecvd=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIBPayingState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUI_Pend=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenStDt=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenEndDt=05%2F05%2F2027&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24lblFIT=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtAmtWK=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtRsnLate=');
  }

  function checkOtherBenefitsPostData(interception) {
    const formData = interception.request.body;
    cy.checkCommonPostData(formData);
    expect(formData).to.include('__EVENTTARGET=&__EVENTARGUMENT=&ContentPlaceHolder1_ClaimantDisabilityTab_ClientState=%7B%22ActiveTabIndex%22%3A5%2C%22TabState%22%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%5D%7D&');
    expect(formData).to.include('ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnPregFlg=N&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtLDW=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnRTWFlg=Y&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtRTW=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtExpRDTW=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnConflictType=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnTDIPayCode=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabDoctor%24hdnInjCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabWC%24hdnNoClaimCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tbpnlLatePayment%24hdnLPay=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDate=05%2F05%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVetDtLast=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerReturn=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerRetWork=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDesc=pregnancy&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocName=Test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocStreet=test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddr2=45+MAIN+STREET++45+MAIN+STREET&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocCity=TRENTON&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip1=07765&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocVerZip=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel=804&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel2=294&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel3=4544&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTelExt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtHospVer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24TxtVerInjWk=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpNm=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCity=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpState=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZipCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjDt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWcComp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWCExp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDeter=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTempWC=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24BtnOBEdit=EDIT&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenefits=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDPayingState=CA&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDStatusPending=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfStartDate=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfEndDate=06%2F11%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSBenf=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDAStatus=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDADate=05%2F01%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIbenfRecvd=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIBPayingState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUI_Pend=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenStDt=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenEndDt=05%2F05%2F2027&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24lblFIT=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtAmtWK=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtRsnLate=');
  }

  function checkPaymentPostData(interception) {
    const formData = interception.request.body;
    cy.checkCommonPostData(formData);
    expect(formData).to.include('__EVENTTARGET=&__EVENTARGUMENT=&ContentPlaceHolder1_ClaimantDisabilityTab_ClientState=%7B%22ActiveTabIndex%22%3A5%2C%22TabState%22%3A%5Bfalse%2Cfalse%2Cfalse%2Cfalse%2Cfalse%2Ctrue%5D%7D&');
    expect(formData).to.include('ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnPregFlg=N&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtLDW=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnRTWFlg=Y&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtRTW=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnDtExpRDTW=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnConflictType=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24Dis1%24hdnTDIPayCode=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabDoctor%24hdnInjCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24TabWC%24hdnNoClaimCount=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tbpnlLatePayment%24hdnLPay=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDate=05%2F05%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVetDtLast=05%2F04%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerReturn=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerRetWork=05%2F27%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDisabDesc=pregnancy&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocName=Test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocStreet=test&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddr2=45+MAIN+STREET++45+MAIN+STREET&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocCity=TRENTON&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip1=07765&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocVerZip=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocAddOOC4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel=804&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel2=294&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTel3=4544&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDocTelExt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmerEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtHospVer=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspStart=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerHspEnd=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24TxtVerInjWk=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpNm=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpadd2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCity=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpState=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip1=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZip2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpZipCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerEmpCountry=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh2=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh3=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjEmpPh4=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerInjDt=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWcComp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerWCExp=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerDeter=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTempWC=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenefits=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDPayingState=CA&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDStatusPending=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfStartDate=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDBenfEndDate=06%2F11%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSBenf=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDAStatus=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDSSDADate=05%2F01%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIbenfRecvd=Yes&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerTDUIBPayingState=NJ&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUI_Pend=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenStDt=05%2F06%2F2026&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtVerUIBenEndDt=05%2F05%2F2027&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24btnVerLatepay=EDIT&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24lblFIT=No&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtAmtWK=&ctl00%24ContentPlaceHolder1%24ClaimantDisabilityTab%24tabpnlDisabilityVerification%24txtRsnLate=');
  }

  function checkInfoEntry(newSubmitButton = false) {
    cy.mockASPX(URL);
    if (newSubmitButton) {
      cy.get('#submitButton').click();
    } else {
      cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_rbtnDisabsYes').click();
      cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_btncontinueVer').click();
    }
    cy.wait('@aspxSubmission').then(checkPostData);
  }

  function checkDisabilityEdit() {
    cy.mockASPX(URL);
    cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnDisInfoEdit').click();
    cy.wait('@aspxSubmission').then(checkDisabilityPostData);
  }

  function checkMedicalEdit() {
    cy.mockASPX(URL);
    cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_btnVerDisab').click();
    cy.wait('@aspxSubmission').then(checkMedicalPostData);
  }

  function checkWorkEdit() {
    cy.mockASPX(URL);
    cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnWREdit').click();
    cy.wait('@aspxSubmission').then(checkWorkPostData);
  }

  function checkOtherBenefitsEdit() {
    cy.mockASPX(URL);
    cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnOBEdit').click();
    cy.wait('@aspxSubmission').then(checkOtherBenefitsPostData);
  }

  function checkPaymentEdit() {
    cy.mockASPX(URL);
    cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_btnVerLatepay').click();
    cy.wait('@aspxSubmission').then(checkPaymentPostData);
  }

  describe("page without new JS", () => {
    beforeEach(() => {
      cy.intercept('**/tdiOverride.min.js', { body: '', disableCache: true }).as('scriptIntercept');
      cy.visit(FIXTURE);
    });

    it("user can input info and proceed to next page", () => {
      checkInfoEntry();
    });

    it("allows user to edit disability information", () => {
      checkDisabilityEdit();
    });

    it("allows user to edit medical treatment information", () => {
      checkMedicalEdit();
    });

    it("allows user to edit work related information", () => {
      checkWorkEdit();
    });

    it("allows user to edit other benefits information", () => {
      checkOtherBenefitsEdit();
    });

    it("allows user to edit payment information", () => {
      checkPaymentEdit();
    });

    globalTestsOld(URL);
  });

  describe("page with new JS", () => {
    beforeEach(() => {
      cy.intercept('GET', '**/tdiOverride.min.js', (req) => {
        req.continue((res) => {
          expect([200, 304]).to.include(res.statusCode);
        });
      }).as('script');
      cy.visit(FIXTURE);
      cy.wait('@script');
    });
    
    afterEach(() => {
      cy.checkBodyA11y(true);
    });

    it('intl doctor names appear', () => {
      cy.visit(FIXTURE_WITH_INTL_DOCTOR);
      cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_txtVerDocName')
        .should('be.visible').and('have.value', 'Dr. Spaceman');
    });

    it("user can input info and proceed to next page", () => {
      checkInfoEntry(true);
      cy.window().then((win) => {
        const encodedData = win.sessionStorage.getItem('session_data');
        const data = JSON.parse(encodeDecode(encodedData));
        expect(data["provider_name"]).to.equal('Test');
      });
    });

    it("allows user to edit leave schedule information (formerly disability information)", () => {
      checkDisabilityEdit();
    });

    it("allows user to edit medical information (formerlly medical treatment information)", () => {
      checkMedicalEdit();
    });

    it("allows user to edit work related information", () => {
      checkWorkEdit();
      cy.window().then((win) => {
        const encodedData = win.sessionStorage.getItem('session_data');
        const data = JSON.parse(encodeDecode(encodedData));
        expect(data["editing_workers_comp"]).to.equal(true);
      });
    });

    it("allows user to edit other benefits information", () => {
      checkOtherBenefitsEdit();
    });

    it("allows user to edit payment information", () => {
      checkPaymentEdit();
    });

    it("Leave Schedule EDIT button sets disabilityInfoView flag to leaveSchedule", () => {
      cy.mockASPX(URL);
      cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnDisInfoEdit').click();
      cy.window().then((win) => {
        const encodedData = win.sessionStorage.getItem('session_data');
        const data = JSON.parse(encodeDecode(encodedData));
        expect(data["disabilityInfoView"]).to.equal('leaveSchedule');
      });
    });

    describe('Reason For Leave Section', () => {
      it("Reason for Leave section with reason exists", () => {
        cy.get('#reasonForLeaveReviewSection').should('exist');
        cy.get('#reasonForLeaveReviewSection legend').should('contain', 'Reason for leave');
        cy.get('#editReasonForLeave').should('exist').and('have.value', 'EDIT');
        cy.get('#reasonForLeaveReviewSection').should('contain', 'Pregnancy and recovery from childbirth');
      });

      it("Reason for Leave edit button sets disabilityInfoView flag to reasonForLeave", () => {
        cy.mockASPX(URL);
        cy.get('#editReasonForLeave').click();
        cy.window().then((win) => {
          const encodedData = win.sessionStorage.getItem('session_data');
          const data = JSON.parse(encodeDecode(encodedData));
          expect(data["disabilityInfoView"]).to.equal('reasonForLeave');
        });
      });

      it("Reason for Leave EDIT button clicks BtnDisInfoEdit and submits form", () => {
        cy.mockASPX(URL);
        cy.get('#editReasonForLeave').click();
        cy.wait('@aspxSubmission').then((interception) => {
          const formData = interception.request.body;
          expect(formData).to.include('BtnDisInfoEdit=EDIT');
        });
      });

    })

    describe('Leave Schedule section', () => {
      it("renames Disability Information to Leave Schedule", () => {
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnDisInfoEdit')
          .closest('fieldset')
          .find('legend')
          .should('contain', 'Leave schedule');
      });

      it("hides the original Leave Schedule table", () => {
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnDisInfoEdit')
          .closest('fieldset')
          .find('table')
          .should('have.css', 'display', 'none');
      });

      it("creates display div with leaveScheduleDisplay id", () => {
        cy.get('#leaveScheduleDisplay').should('exist');
      });

      it("shows Last workday label first", () => {
        cy.get('#leaveScheduleDisplay p').first().should('contain', 'Last workday:');
      });

      it("shows First day of disability leave for reason in text based on user's disability reason", () => {
        cy.window().then((win) => {
          const data = { reason_for_leave: EXAMPLE_REASON_FOR_LEAVE_DATA_INJURY_DETAILS };
          win.sessionStorage.setItem("session_data", encodeDecode(JSON.stringify(data)));
        });
        cy.visit(FIXTURE);
        cy.wait('@script');
        cy.get('#leaveScheduleDisplay').should('contain', 'First day of disability leave for injury:');
      });

      it("displays the correct schedule values from the hidden form fields", () => {
        cy.get('#leaveScheduleDisplay').should('contain', '05/04/2026'); // Last workday
        cy.get('#leaveScheduleDisplay').should('contain', '05/05/2026'); // First day disability
        cy.get('#leaveScheduleDisplay').should('contain', 'Yes');         // Returned to work
        cy.get('#leaveScheduleDisplay').should('contain', '05/27/2026'); // Recovery date
      });

      it("Leave Schedule EDIT button submits form with BtnDisInfoEdit", () => {
        cy.mockASPX(URL);
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnDisInfoEdit').click();
        cy.wait('@aspxSubmission').then((interception) => {
          const formData = interception.request.body;
          expect(formData).to.include('BtnDisInfoEdit=EDIT');
        });
      });
    });

    describe('Medical Details Section', () => {
      it("renames Medical Treatment Information to Medical Details", () => {
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_btnVerDisab')
          .closest('fieldset')
          .find('legend')
          .should('contain', 'Medical details');
      });

      it("hides Disability/Injury Description table from Medical section", () => {
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_txtVerDisabDesc')
          .closest('table')
          .should('have.css', 'display', 'none');
      });
    })

    describe('Work Related Information Section', () => {
      it("shows formatted Work related information", () => {
        cy.window().then((win) => {
          win.sessionStorage.setItem("session_data", encodeDecode(JSON.stringify({ reason_for_leave: { reasons: 'injury' } })));
        });
        cy.intercept('GET', '**/tdiOverride.min.js', (req) => {
          req.continue((res) => {
            expect([200, 304]).to.include(res.statusCode);
          });
        }).as('script');
        cy.visit(FIXTURE_WITH_WORKERS_COMP_YES);
        cy.get('#workRelatedDisplay')
          .should('contain.text', "File or intend to file Workers' Compensation claim:")
          .and('contain.text', 'Yes');
        cy.get('#workRelatedDisplay')
          .should('contain.text', 'Employer information where the injury happened');
        cy.get('#workRelatedDisplay').should('contain.text', 'Name:');
        cy.get('#workRelatedDisplay').should('contain.text', 'Address:');
        cy.get('#workRelatedDisplay')
          .should('contain.text', 'Phone:')
          .and('contain.text', 'ext.');
        cy.get('#workRelatedDisplay').should('contain.text', 'Date of injury:');
        cy.get('#workRelatedDisplay')
          .should('contain.text', 'Approved for Workers\' Compensation benefits');
        cy.get('#workRelatedDisplay')
          .should('contain.text', 'Receiving benefits same time as TDI:');
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnWREdit')
          .closest('fieldset')
          .find('> table')
          .should('not.be.visible');
        cy.get('#divVerRelatedInfo').should('not.be.visible');
      });

      it('formats workers comp phone number as (XXX) XXX-XXXX', () => {
        cy.window().then((win) => {
          win.sessionStorage.setItem("session_data", encodeDecode(JSON.stringify({ reason_for_leave: { reasons: 'injury' } })));
        });
        cy.intercept('GET', '**/tdiOverride.min.js', (req) => {
          req.continue((res) => {
            expect([200, 304]).to.include(res.statusCode);
          });
        }).as('script');
        cy.visit(FIXTURE_WITH_WORKERS_COMP_YES);
        cy.get('#workRelatedDisplay')
          .invoke('text')
          .should('match', /\(\d{3}\) \d{3}-\d{4}/);
      });

      it('displays "injury" in workers comp text when reason is injury', () => {
        cy.window().then((win) => {
          win.sessionStorage.setItem("session_data", encodeDecode(JSON.stringify({ reason_for_leave: { reasons: 'injury' } })));
        });
        cy.intercept('GET', '**/tdiOverride.min.js', (req) => {
          req.continue((res) => {
            expect([200, 304]).to.include(res.statusCode);
          });
        }).as('script');
        cy.visit(FIXTURE_WITH_WORKERS_COMP_YES);
        cy.wait('@script');
        cy.get('#workRelatedDisplay')
          .should('contain.text', 'injury happened')
          .and('contain.text', 'Date of injury');
        
        cy.contains("Approved for Workers' Compensation benefits: Yes").should('be.visible');
        cy.contains("Receiving benefits same time as TDI: No").should('be.visible');
      });

      it('hides entire section when reason is pregnancy', () => {
        cy.window().then((win) => {
          win.sessionStorage.setItem("session_data", encodeDecode(JSON.stringify({ reason_for_leave: { reasons: 'pregnancy' } })));
        });
        cy.intercept('GET', '**/tdiOverride.min.js', (req) => {
          req.continue((res) => {
            expect([200, 304]).to.include(res.statusCode);
          });
        }).as('script');
        cy.visit(FIXTURE);
        cy.wait('@script');
        cy.get('#ContentPlaceHolder1_ClaimantDisabilityTab_tabpnlDisabilityVerification_BtnWREdit').should('not.be.visible');
      });

      it('hides "received benefits" when not approved for benefits', () => {
        cy.intercept('GET', '**/tdiOverride.min.js', (req) => {
          req.continue((res) => {
            expect([200, 304]).to.include(res.statusCode);
          });
        }).as('script');
        cy.visit(FIXTURE_WITH_NOT_APPROVED_BUT_RECEIVED_WC);
        cy.wait('@script');
        cy.contains("Approved for Workers' Compensation benefits: No").should('be.visible');
        cy.contains("Receiving benefits same time as TDI: Yes").should('not.exist');
      });
    });

    globalTestsNew(PAGE_ID, URL);
  });
});
