name: Deploy to Beta

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Choose the environment to deploy'
        required: true
        default: 'dev'
        options:
          - prod
          - dev
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variable
      id: set-env
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "environment=dev" >> $GITHUB_OUTPUT
        else
          echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
        fi

    - name: Generate GitHub App Token
      id: generate-token
      uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      with:
        app-id: "2454947"
        private-key: ${{ secrets.OOI_PULL_REQUEST_APP }}

    - name: Checkout the correct branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.environment }}
        token: ${{ steps.generate-token.outputs.token }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Checkout beta repo
      uses: actions/checkout@v3
      with:
        repository: newjersey/beta
        token: ${{ steps.generate-token.outputs.token }}
        path: beta
        ref: master

    - name: Run prep-deploy script based on environment
      run: npm run prep-deploy-${{ inputs.environment }}

    - name: Commit and push changes to beta repo
      run: |
        cd beta
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        latest_commit=$(git --git-dir=../.git rev-parse ${{ inputs.environment }})
        git add .
        git commit -m "TDI ${{ inputs.environment }}. Latest commit: $latest_commit" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/newjersey/beta.git
        git push origin master
